# Generated by Django 5.2 on 2025-05-07 00:29

import appoint_app.models
import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre', models.CharField(choices=[('Kakdwip', 'Kakdwip'), ('5_No_Hat', '5 No. Hat')], max_length=50)),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednessday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('allowed', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)])),
                ('centre', models.CharField(choices=[('Kakdwip', 'Kakdwip'), ('5_No_Hat', '5 No. Hat')], verbose_name='Centre')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('allowed', models.PositiveIntegerField()),
                ('booked', models.PositiveIntegerField(default=0)),
                ('vacent', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('payment', models.BooleanField(blank=True, choices=[(True, 'Verified'), (False, 'N/A')], default=False, null=True, verbose_name='Payment')),
                ('appoint_id', models.CharField(default=appoint_app.models.generate_appointment_id, editable=False, max_length=6, primary_key=True, serialize=False, verbose_name='Appointment ID')),
                ('book_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Booked on')),
                ('approve_date', models.DateTimeField(blank=True, null=True, verbose_name='Approved on')),
                ('doctor_remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('appoint_status', models.CharField(choices=[('', '-----'), ('Failed', 'Failed'), ('Scheduled', 'Scheduled'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], max_length=10, verbose_name='Status')),
                ('appointee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patients', to='account.patient')),
                ('queue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='appoint_app.queue')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Slot', to='appoint_app.slot')),
            ],
        ),
    ]
