# Generated by Django 5.2 on 2025-05-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='queue',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Queue'),
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
