# Generated by Django 5.2 on 2025-05-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint_app', '0002_alter_appointment_queue_delete_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='queue',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Queue'),
        ),
    ]
