# Generated by Django 5.2 on 2025-05-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appoint_app', '0003_alter_appointment_queue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='vacent',
        ),
    ]
